# -*- coding: utf-8 -*-
"""Copy of Assignment_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k-_NzQAfzXOUHxKKLiJJXq4veLnTiZ-U
"""

import pandas as pd
df = pd.read_csv('facebook.csv', sep=';')
df.head()

subset_df = df[['Type', 'Category', 'Lifetime Post Impressions by people who have liked your Page']]
Photo_data = df[df['Type'] == 'Photo']



merged_df = pd.merge(subset_df,Photo_data, on='Type')

merged_df.head()

sort_df = df.sort_values(by='Lifetime Post Impressions by people who have liked your Page')
sort_df = df.sort_values(by='Lifetime Post Impressions by people who have liked your Page',ascending=False)
sort_df.head()

transpose_df = merged_df.T
transpose_df.head()

rows, cols = df.shape
print(rows, cols)

#Basically changes the DataFrame into a NumPy array and rearranges its shape.
# =>Converts the tabular data (DataFrame) into a plain NumPy array
# =>Reshapes it into a different structure (e.g., 19 columns)
# =>Removes row/column labels — it's now just numbers in a matrix-like form

import numpy as np
reshaped_arr = np.array(df).reshape(-1, 19)

reshaped_arr

reshaped_arr.shape
