# -*- coding: utf-8 -*-
"""Copy of Assignment _7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcgbrvIzzycN0TCqBfIyVCJJaB-WeR7Y
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('forestfire.csv')
df.head()

"""**MATPLOTLIB**"""

# Line Graph
area_burned_per_month = df.groupby('month')['area'].mean()
plt.plot(area_burned_per_month.index, area_burned_per_month.values)
plt.xlabel('Month')
plt.ylabel('Average Area Burned')
plt.show()

# Histogram
plt.hist(df['area'], bins=30)
plt.xlabel('Area')
plt.ylabel('Frequency')
plt.show()

#| `bins` value      | Meaning                     |
#| ----------------- | --------------------------- |
#| Small (e.g., 10)  | Broad view of distribution  |
#| Large (e.g., 100) | Fine detail, possible noise |

# Bar Chart
fires_per_month = df['month'].value_counts()
plt.bar(fires_per_month.index, fires_per_month.values, color='red')
plt.xlabel('Month')
plt.ylabel('Area Burned')
plt.show()

# BoxPlot
df.boxplot(column='temp', by='month')
plt.xlabel('Month')
plt.ylabel('Area Burned')
plt.show()

"""**SEABORN**"""

# Month-wise fire count
sns.countplot(x='month', data=df)
plt.show()

# Temperature vs Area burned (scatter plot)
sns.scatterplot(x='area', y='temp', data=df)
plt.show()

# Correlation heatmap
df1 = df.drop(['month', 'day'], axis = 1)
plt.figure(figsize=(10,7))
sns.heatmap(df1.corr(), annot=True)
plt.show()

sns.distplot(df['area'])
plt.show()